### ISSUE TITLE
poetry command not found

### ISSUE THREAD

**Issue by zlzhao124** [wustl-data/hw0-environment#2]
Hi Dr. Schlichenmeyer! I was able to get all the way to connecting VS Code with my repository, however after that when I went to try and install the project dependencies, I got stuck because it says the poetry command is not found. I looked online for a bit and it seems the poetry command only works for one version of python, which isn't the one we're working through. Is there any way to get around this? Thanks!

**Comment by lydiareader** [comment]
You might need to add poetry to PATH. Do you have a mac? If you have a mac I recommend installing poetry with Homebrew because it will automatically add poetry to PATH for you. You can type
brew install poetry 
in the terminal

**Comment by schlich** [comment]
Lydia's suggestion is a good suggestion... Homebrew usually makes installation much easier on macs.

If you're working with Windows Subsystem for Linux, try installing the script using the `python` command instead of the `python3` command as provided in the instructions, so your install command would be:
`$ curl -sSL https://install.python-poetry.org | python -`
instead of:
`$ curl -sSL https://install.python-poetry.org | python3 -`
This should use the python version activated by Pyenv instead of the python version you have installed for `python3`.

If that still fails, try using the installer for an older version of Poetry: 

`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`

Hope that helps!

**Comment by zlzhao124** [comment]
I'm using a mac, so Lydia's thing helped the most. Thanks a lot!!
